### ISSUE TITLE
Is this still usable?

### ISSUE THREAD

**Issue by kosta1221** [negasus/traefik2-luascript#4]
From seeing that traefik supports custom plugins, I guess there's no real need for this anymore?

However, I would like to write a quick lua middleware as a demo and test it out. Is it still possible?

I'm getting the following error:

```bash
$ go build -o ./traefik ./cmd/traefik

pkg/server/middleware/middlewares.go:32:2: no required module provides package github.com/containous/traefik/v2/pkg/middlewares/luascript; to add it:
        go get github.com/containous/traefik/v2/pkg/middlewares/luascript
webui/embed.go:8:12: pattern static: no matching files found
```

Feedback would be appreciated,
Kosta

**Comment by negasus** [comment]
I have to check it, because this demonstration was written Quite a long time ago. And there is probability that changes in the Traefik made some incompatibility

**Comment by kosta1221** [comment]
Thank you! I've moved from this for now but an update will be appreciated :)

**Comment by negasus** [comment]
I updated the readme, and the demo is works fine )
